import{Customer} from './customer'
import{Orders} from './orders'
export const CUSTOMERDETAILS:Customer={
    "kkdCustId": "KKDCUST2000",
    "mobileNo": "7418832509",
    "password": null,
    "firstName": "string",
    "lastName": "string",
    "addresses": [
      {
        "pincode": 0,
        "addressLine": "string",
        "city": "string",
        "district": "string",
        "state": "string",
        "primary": false
      }
    ],
    "primaryAddress": {
      "pincode": 0,
      "addressLine": "string",
      "city": "string",
      "district": "string",
      "state": "string",
      "primary": false
    },
    "role": "Customer",
    "bankDetails": null
  };
  export const CUSTOMERDETAILSNEGATIVE:Customer={
    "kkdCustId": "KKDCUST2001",
    "mobileNo": "8098433601",
    "password": null,
    "firstName": "Murali",
    "lastName": "string",
    "addresses": [
      {
        "pincode": 0,
        "addressLine": "string",
        "city": "string",
        "district": "string",
        "state": "string",
        "primary": false
      }
    ],
    "primaryAddress": {
      "pincode": 0,
      "addressLine": "string",
      "city": "string",
      "district": "string",
      "state": "string",
      "primary": false
    },
    "role": "Customer",
    "bankDetails": null
  }
  export const DETAILS: Customer = {
    "kkdCustId": "KKDCUST2000",
    "mobileNo": "7418832509",
    "password": null,
    "firstName": "Sridharan",
    "lastName": "string",
    "addresses": [
      {
        "pincode": 0,
        "addressLine": "string",
        "city": "string",
        "district": "string",
        "state": "string",
        "primary": false
      }
    ],
    "primaryAddress": {
      "pincode": 0,
      "addressLine": "string",
      "city": "string",
      "district": "string",
      "state": "string",
      "primary": false
    },
    "role": "Customer",
    "bankDetails": null
  };

  export const NEGATIVEDETAILS: Customer = {
    "kkdCustId": "KKDCUST2001",
    "mobileNo": "8098433601",
    "password": null,
    "firstName": "Murali",
    "lastName": "string",
    "addresses": [
      {
        "pincode": 0,
        "addressLine": "string",
        "city": "string",
        "district": "string",
        "state": "string",
        "primary": false
      }
    ],
    "primaryAddress": {
      "pincode": 0,
      "addressLine": "string",
      "city": "string",
      "district": "string",
      "state": "string",
      "primary": false
    },
    "role": "Customer",
    "bankDetails": null
  }
  export const CURRENTORDERS : Orders[] =[
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4013",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "12:05:00",
      "expectedDate": "2018-05-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "9411",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4014",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "3294",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4015",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "0524",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4016",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "7357",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4017",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "5533",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    }
  ];

  export const CURRENTORDERSNEGATIVE : Orders[] =[
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4013",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "12:05:00",
      "expectedDate": "2018-05-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "9411",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4014",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "3294",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4015",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "0524",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4016",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "7357",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4017",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": null,
      "expectedDate": "2018-04-27",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Current",
      "orderStatus": null,
      "otp": "5533",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    }
  ]
  export const PREVIOUSORDERS : Orders[] =[
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4002",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-22",
      "mobileNo": "9813887587",
      "transactionId": "kkdtrans5001",
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "5678",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "I am not in a good health condition"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4003",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "5678",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "The order quantity is not sufficient"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4005",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "5678",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4006",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "4823",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "Other reasons"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4007",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "2995",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "The order quantity is not sufficient"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4008",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "05:45:00",
      "expectedDate": "2018-04-22",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "0021",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4009",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "15:35:00",
      "expectedDate": "2018-05-24",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "1795",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4010",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "6820",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "I am not in a good health condition"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4011",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "02:00:00",
      "expectedDate": "2018-05-01",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "9198",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3001",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4012",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "01:00:00",
      "expectedDate": "2018-05-02",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "7886",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    }
  ];


  export const PREVIOUSORDERSNEGATIVE : Orders[] =[
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4002",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-22",
      "mobileNo": "9813887587",
      "transactionId": "kkdtrans5001",
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "5678",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "I am not in a good health condition"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4003",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "5678",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "The order quantity is not sufficient"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4005",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "15:45:00",
      "expectedDate": "2018-04-28",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "5678",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4006",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "4823",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "Other reasons"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4007",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "2995",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "The order quantity is not sufficient"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4008",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "05:45:00",
      "expectedDate": "2018-04-22",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "0021",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4009",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "15:35:00",
      "expectedDate": "2018-05-24",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "1795",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4010",
      "quantity": 10,
      "farmerStatus": "Decline",
      "expectedTime": null,
      "expectedDate": null,
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Cancelled",
      "otp": "6820",
      "otpVerified": null,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": "I am not in a good health condition"
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4011",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "02:00:00",
      "expectedDate": "2018-05-01",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "9198",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    },
    {
      "kkdFarmId": "kkdfarm1001",
      "productId": "kkdprod2001",
      "kkdCustId": "kkdcust3002",
      "name": "nishant",
      "address": {
        "pincode": 127306,
        "addressLine": "306 street A",
        "city": "dundahera",
        "district": "gurugram",
        "state": "haryana"
      },
      "avgRating": 5,
      "orderId": "KKDORD4012",
      "quantity": 10,
      "farmerStatus": "Accept",
      "expectedTime": "01:00:00",
      "expectedDate": "2018-05-02",
      "mobileNo": "9813887587",
      "transactionId": null,
      "totalAmount": 500,
      "orderType": "Previous",
      "orderStatus": "Delivered",
      "otp": "7886",
      "otpVerified": true,
      "orderPlacingDate": "2018-04-05",
      "orderReceivingDate": null,
      "validityOfOrder": null,
      "orderDeclineReason": null
    }
  ]
  export const USERDETAILS ={
    "currentPassword": "Sapient@1234",
    "newPassword": "Sriz3196@",
    "userId": "KKDCUST2000"
  };
  
 
  export const USERDETAILSDELETE={
    "mobileNo": "9468075105",
    "password": "Sriz3196@",
  };